# Generated by Django 5.2.7 on 2025-11-14 16:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_trainer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MathChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название испытания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('challenge_type', models.CharField(choices=[('speed', 'Скоростной'), ('accuracy', 'На точность'), ('endurance', 'На выносливость'), ('combo', 'Комбинированный')], max_length=20, verbose_name='Тип испытания')),
                ('operation', models.CharField(choices=[('addition', 'Сложение'), ('subtraction', 'Вычитание'), ('multiplication', 'Умножение'), ('division', 'Деление'), ('mixed', 'Смешанные операции')], max_length=20, verbose_name='Операция')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный'), ('expert', 'Эксперт')], max_length=10, verbose_name='Сложность')),
                ('target_score', models.IntegerField(default=0, verbose_name='Целевой счет')),
                ('target_accuracy', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Целевая точность (%)')),
                ('time_limit', models.IntegerField(default=0, verbose_name='Лимит времени (сек)')),
                ('reward_points', models.IntegerField(default=0, verbose_name='Очки награды')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное испытание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
            ],
            options={
                'verbose_name': 'Математическое испытание',
                'verbose_name_plural': 'Математические испытания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMathProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_experience', models.IntegerField(default=0, verbose_name='Общий опыт')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Уровень')),
                ('current_points', models.IntegerField(default=0, verbose_name='Текущие очки')),
                ('achievements', models.JSONField(blank=True, default=dict, verbose_name='Достижения')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
                ('operation_stats', models.JSONField(blank=True, default=dict, verbose_name='Статистика по операциям')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Профиль математического тренажера',
                'verbose_name_plural': 'Профили математического тренажера',
            },
        ),
        migrations.AlterModelOptions(
            name='mathscore',
            options={'ordering': ['-created_at'], 'verbose_name': 'Результат математического тренажера', 'verbose_name_plural': 'Результаты математического тренажера'},
        ),
        migrations.AlterModelOptions(
            name='mathsession',
            options={'ordering': ['-start_time'], 'verbose_name': 'Сессия математического тренажера', 'verbose_name_plural': 'Сессии математического тренажера'},
        ),
        migrations.RemoveField(
            model_name='mathsession',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='mathscore',
            name='average_time_per_question',
            field=models.FloatField(default=0.0, verbose_name='Среднее время на вопрос'),
        ),
        migrations.AddField(
            model_name='mathscore',
            name='max_streak',
            field=models.IntegerField(default=0, verbose_name='Максимальная серия'),
        ),
        migrations.AddField(
            model_name='mathscore',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дополнительные метрики'),
        ),
        migrations.AddField(
            model_name='mathsession',
            name='current_answer',
            field=models.FloatField(blank=True, null=True, verbose_name='Правильный ответ'),
        ),
        migrations.AddField(
            model_name='mathsession',
            name='current_question',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текущий вопрос'),
        ),
        migrations.AddField(
            model_name='mathsession',
            name='current_score',
            field=models.IntegerField(default=0, verbose_name='Текущий счет'),
        ),
        migrations.AddField(
            model_name='mathsession',
            name='current_streak',
            field=models.IntegerField(default=0, verbose_name='Текущая серия'),
        ),
        migrations.AddField(
            model_name='mathsession',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный'), ('expert', 'Эксперт')], default='easy', max_length=10, verbose_name='Сложность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathsession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная сессия'),
        ),
        migrations.AddField(
            model_name='mathsession',
            name='operation',
            field=models.CharField(choices=[('addition', 'Сложение'), ('subtraction', 'Вычитание'), ('multiplication', 'Умножение'), ('division', 'Деление'), ('mixed', 'Смешанные операции')], default='easy', max_length=20, verbose_name='Операция'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathsession',
            name='session_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные сессии'),
        ),
        migrations.AddField(
            model_name='mathsession',
            name='session_max_streak',
            field=models.IntegerField(default=0, verbose_name='Максимальная серия в сессии'),
        ),
        migrations.AlterField(
            model_name='mathscore',
            name='correct_answers',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Правильные ответы'),
        ),
        migrations.AlterField(
            model_name='mathscore',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mathscore',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный'), ('expert', 'Эксперт')], max_length=10, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='mathscore',
            name='operation',
            field=models.CharField(choices=[('addition', 'Сложение'), ('subtraction', 'Вычитание'), ('multiplication', 'Умножение'), ('division', 'Деление'), ('mixed', 'Смешанные операции')], max_length=20, verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='mathscore',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='mathscore',
            name='time_spent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Затраченное время (сек)'),
        ),
        migrations.AlterField(
            model_name='mathscore',
            name='total_questions',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Всего вопросов'),
        ),
        migrations.AlterField(
            model_name='mathscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='math_scores', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='mathsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='mathsession',
            name='session_type',
            field=models.CharField(choices=[('practice', 'Тренировка'), ('timed', 'На время'), ('endless', 'Бесконечный режим'), ('challenge', 'Испытание')], default='practice', max_length=20, verbose_name='Тип сессии'),
        ),
        migrations.AlterField(
            model_name='mathsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='mathsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='math_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='mathscore',
            index=models.Index(fields=['user', 'operation'], name='math_traine_user_id_ca99fa_idx'),
        ),
        migrations.AddIndex(
            model_name='mathscore',
            index=models.Index(fields=['user', 'difficulty'], name='math_traine_user_id_28999e_idx'),
        ),
        migrations.AddIndex(
            model_name='mathscore',
            index=models.Index(fields=['created_at'], name='math_traine_created_c30c62_idx'),
        ),
        migrations.AddConstraint(
            model_name='mathscore',
            constraint=models.CheckConstraint(condition=models.Q(('correct_answers__lte', models.F('total_questions'))), name='correct_answers_lte_total_questions'),
        ),
        migrations.AddField(
            model_name='usermathprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='math_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
