# Generated by Django 5.2.7 on 2025-11-14 16:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'Общие знания'), ('science', 'Наука'), ('history', 'История'), ('geography', 'География'), ('entertainment', 'Развлечения')], max_length=20, verbose_name='Категория')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=10, verbose_name='Сложность')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('options', models.JSONField(verbose_name='Варианты ответов')),
                ('correct_answer', models.IntegerField(verbose_name='Индекс правильного ответа')),
                ('explanation', models.TextField(blank=True, verbose_name='Объяснение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вопрос викторины',
                'verbose_name_plural': 'Вопросы викторины',
                'ordering': ['category', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='HangmanGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='Загаданное слово')),
                ('current_state', models.CharField(max_length=100, verbose_name='Текущее состояние')),
                ('used_letters', models.CharField(blank=True, default='', max_length=100, verbose_name='Использованные буквы')),
                ('mistakes', models.IntegerField(default=0, verbose_name='Количество ошибок')),
                ('max_mistakes', models.IntegerField(default=6, verbose_name='Максимальное количество ошибок')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('won', 'Выиграна'), ('lost', 'Проиграна')], default='active', max_length=10, verbose_name='Статус игры')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игра в виселицу',
                'verbose_name_plural': 'Игры в виселицу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'Общие знания'), ('science', 'Наука'), ('history', 'История'), ('geography', 'География'), ('entertainment', 'Развлечения')], max_length=20, verbose_name='Категория')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=10, verbose_name='Сложность')),
                ('score', models.IntegerField(default=0, verbose_name='Счет')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Всего вопросов')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Правильные ответы')),
                ('completed_questions', models.JSONField(default=list, verbose_name='Завершенные вопросы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная сессия')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.quizquestion', verbose_name='Текущий вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия викторины',
                'verbose_name_plural': 'Сессии викторины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('rps', 'Камень-Ножницы-Бумага'), ('hangman', 'Виселица'), ('quiz', 'Викторина'), ('memory', 'Игра на память')], max_length=20, verbose_name='Тип игры')),
                ('score', models.IntegerField(default=0, verbose_name='Счет')),
                ('result', models.CharField(choices=[('win', 'Победа'), ('lose', 'Поражение'), ('draw', 'Ничья')], max_length=10, verbose_name='Результат')),
                ('game_data', models.JSONField(blank=True, default=dict, verbose_name='Данные игры')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность (сек)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'game_type'], name='games_games_user_id_ed11fb_idx'), models.Index(fields=['created_at'], name='games_games_created_d9e63a_idx')],
            },
        ),
    ]
